name: Compile Firmware (quick)

on:
  push

jobs:
  Build:
    runs-on: ubuntu-latest

    container: d3xter93/sonix_base_container

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: pip3 install -r requirements.txt
    - name: Build Sonix keyboards on quickbuild list
      run:  python3 lib/python/build_all.py --whitelist quickbuild_whitelist
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Pre-Compiled Firmware
        path: '*.bin'
